export const TRADINGS =
  'AAA AAS AAT AAV ABB ABS ACB AFX AGM AGR AMV ANV APG APH API APS ASM BAF BCC BCG BID BII BMI BOT BSI BSR BVB BVH BVS C47 C4G CAT CDC CEN CEO CII CMG CMX CRE CSV CTC CTD CTF CTG CTI CTR CTS DAG DAH DBC DCL DCM DDG DDV DGC DGW DHC DHM DIG DL1 DLG DPG DPM DPR DRC DRH DRI DTD DVG DXG DXS E1VFVN30 EIB ELC EVF EVG EVS FCN FIR FIT FPT FRT FTS FUEVFVND G36 GAS GEG GEX GIL GMD GVR HAG HAH HAX HBC HCD HCM HDB HDC HDG HHP HHG HHV HHS HID HNG HPG HPX HQC HSG HT1 HTN HUT HVA HVH HVN IBC IDC IDI IDJ IJC IPA ITA ITC JVC KBC KDC KDH KHG KOS KPF KSB L14 LAS LCG LCM LDG LGL LHC LIG LMH LPB MBB MBG MBS MCM MIG MSB MSN MST MWG NAG NBB NHA NHH NHV NKG NLG NRC NT2 NTL NVL OCB OIL OGC OCH ORS PAN PC1 PDR PET PFL PHC PHR PLC PLX PNJ POM POW PSH PVB PVC PVD PVL PVP PVS PVT PXL PXS QBS QCG QNS QTP REE S99 SAB SAM SBS SBT SCG SCR SHB SHI SHS SJF SKG SMC SRA SSB SSI SSH SSN STB STK SZC TAR TCB TCD TCH TCI TCM TDC TDM TEG TGG TIG TLG TLH TNG TNT TPB TSB TSC TTB TTA TTF TTH TVB TVC TVN VC2 VC3 VCB VCG VCI VDS VGC VGI VGT VGS VHC VHE VHG VHM VIB VIC VIG VIP VIX VJC VKC VND VNE VNM VPB VOS VPG VPI VRE VSH VTP VUA'.split(
    ' ',
  );
export const TICKERS =
  'HOSE HNX HOSE HNX HNX HOSE HOSE HNX HOSE HOSE HNX HOSE HOSE HOSE HNX HNX HOSE HOSE HNX HOSE HOSE HNX HOSE HNX HOSE HNX HNX HOSE HNX HOSE HNX HNX HOSE HNX HNX HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HNX HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HNX HNX HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HNX HOSE HOSE HOSE HNX HOSE HNX HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HNX HOSE HNX HOSE HOSE HNX HNX HNX HOSE HOSE HNX HNX HNX HOSE HOSE HOSE HNX HOSE HNX HOSE HOSE HOSE HNX HOSE HOSE HNX HOSE HOSE HOSE HOSE HNX HOSE HNX HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HNX HNX HOSE HNX HOSE HNX HOSE HNX HNX HOSE HOSE HNX HNX HOSE HNX HOSE HOSE HNX HOSE HNX HOSE HOSE HOSE HNX HOSE HOSE HOSE HNX HOSE HOSE HNX HNX HOSE HOSE HOSE HNX HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HNX HOSE HOSE HNX HOSE HOSE HNX HOSE HOSE HOSE HOSE HNX HOSE HNX HNX HNX HNX HOSE HOSE HOSE HOSE HOSE HNX HNX HNX HOSE HNX HNX HOSE HOSE HOSE HNX HOSE HOSE HOSE HNX HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HOSE HNX HNX'.split(
    ' ',
  );

export const COLORS = [
  '#90f8b4',
  '#95c181',
  '#51e7b2',
  '#d848fa',
  '#7c12e1',
  '#6ae52b',
  '#3cae6e',
  '#370d16',
  '#3bfa5a',
  '#a8706b',
  '#cd9782',
  '#91257d',
  '#56c4e8',
  '#befa72',
  '#8576e8',
  '#d5996b',
  '#c1a4bd',
  '#93d9c5',
  '#a5a96b',
  '#d993c7',
  '#1f15a4',
  '#763167',
  '#632b40',
  '#f1c8ad',
  '#8fdd22',
  '#2f9b24',
  '#eed14c',
  '#620e47',
  '#5bcfbb',
  '#ab7029',
  '#4c08af',
  '#d98bd0',
  '#013793',
  '#9fa9dc',
  '#6bcc1d',
  '#4849c5',
  '#1cbd02',
  '#24f866',
  '#e260d9',
  '#146425',
  '#b8575e',
  '#1ebce5',
  '#39e6c7',
  '#4b0470',
  '#d379cf',
  '#e2482e',
  '#e271a5',

  '#341366',
  '#40744b',
  '#35546c',
  '#74c678',
  '#43c970',
  '#534bb8',
  '#65bcbe',
  '#ef62cf',
  '#85fcc2',
  '#3b2834',
  '#1703e3',
  '#800c83',
  '#e33698',
  '#a5b28d',
  '#3596b0',
  '#149280',
  '#a29b7e',
  '#f7bd4e',
  '#91ef7b',
  '#7bf3e2',
  '#5942bd',
  '#6054e8',
  '#a8b63f',
    '#dd6863',
  '#1b1c48',
  '#7d660b',
  '#7d02e4',
  '#80c6bf',
  '#66cc0b',
  '#e7b4f2',
  '#972490',
  '#4d0284',
  '#18e84b',
  '#a0de03',
  '#2b06d7',
  '#f24be4',
  '#8f0346',
  '#60372e',
  '#8a1f14',
  '#1add25',
  '#95732f',
  '#38f8a6',
  '#1869c3',
  '#387cb2',
  '#add73b',
  '#84744c',
  '#c418cd',
  '#638f66',
  '#c4052e',
  '#f43cb2',
  '#a7b77d',
  '#600940',
  '#d6184a',
  '#d3e674',
  '#bf27cb',
  '#7b18de',
  '#a0eb5a',
  '#300f75',
  '#c8f620',
  '#d1e07c',
  '#0fd51a',
  '#92f5ac',
  '#8bcf22',
  '#aab9db',
  '#ba0d27',
  '#10de4e',
  '#726597',
  '#9cfdf7',
  '#abd554',
  '#5c24fc',
  '#560827',
  '#82cf8f',
  '#ba3492',
  '#9aae75',
  '#d598e1',
  '#a27e4d',
  '#5695cc',
  '#70f919',
  '#39b784',
  '#46384e',
  '#6fb534',
  '#49abc6',
  '#eaba4f',
  '#64092d',
  '#80208e',
  '#3f1537',
  '#bbdf42',
  '#c57be0',
  '#16d3e8',
  '#f9b85e',
  '#1239c3',
  '#2f75f7',
  '#716cbe',
  '#4df37a',
  '#bfdf05',
  '#5bb5e3',
  '#7ffe0f',
  '#3e2916',
  '#bbdd91',
  '#a4a2b2',
  '#89356d',
  '#e395f3',
  '#30ff18',
  '#93f54c',
  '#117b5f',
  '#97c1df',
  '#3342b7',
  '#ad18aa',
  '#c70c7c',
  '#66f474',
  '#bf657c',
  '#f19688',
  '#38b7c0',
  '#3aa363',
  '#d5f611',
  '#cb208e',
  '#6f7c56',
  '#a0f4aa',
  '#47cc29',
  '#f69182',
  '#0313ab',
  '#7d38ad',
  '#de7c95',
  '#cf3b58',
  '#86d671',
  '#4b404e',
  '#25d49b',
  '#c0c6d5',
  '#ff281e',
  '#671caa',
  '#bd3210',
  '#287973',
  '#7b3ecb',
  '#f9062f',
  '#eb3016',
  '#10a896',
  '#166fbd',
  '#afee97',
  '#357b03',
  '#e77970',
  '#a9735e',
  '#91ce07',
  '#f51243',
  '#890d2b',
  '#d7c133',
  '#31a6de',
  '#94d7a4',
  '#d3e966',
  '#8f0951',
  '#3cc146',
  '#0bb827',
  '#8ba74b',
  '#ffb0d4',
  '#6f3bda',
  '#3af15f',
  '#6f4000',
  '#ed303b',
  '#6de75d',
  '#4f6b53',
  '#6d3e22',
  '#4a9e20',
  '#d2680b',
  '#6aa561',
  '#84ec1a',
  '#6365c3',
  '#8ff99e',
  '#ce88ca',
  '#d62fff',
  '#287b57',
  '#1a8073',
  '#9c13ab',
  '#6ffe29',
  '#ebdb42',
  '#964738',
  '#3d3bf4',
  '#302883',
  '#c3d4c7',
  '#c7a410',
  '#ba6f33',
  '#906cc7',
  '#87a0e5',
  '#71a27a',
  '#e6fb9e',
  '#51a9ab',
  '#01b2a1',
  '#4f3486',
  '#91327b',
  '#477b6b',
  '#b367fa',
  '#87d25a',
  '#4b1e54',
  '#f812e6',
  '#c7ba1c',
  '#0b3986',
  '#c18768',
  '#ae6296',
  '#59de50',
  '#a2cb68',
  '#02383d',
  '#70df27',
  '#293552',
  '#108e9a',
  '#0278ca',
  '#5de37a',
  '#c969c1',
  '#76bbc5',
  '#c29b0e',
  '#e4db96',
  '#8397fb',
  '#acd38d',
  '#1756a6',
  '#ad21fe',
  '#defee6',
  '#cb0ed9',
  '#924869',
  '#8cb40b',
  '#feb1d9',
  '#1931db',
  '#812508',
  '#cbe798',
  '#1fac90',
  '#1d37d9',
  '#ba6e71',
  '#71072f',
  '#dd656e',
];

const names = [
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Cong ty chung khoan',
  'Ban le Do may mac',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Ngan hang',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Ngan hang',
  'San pham thuc pham',
  'San pham thuc pham',
  'Cong ty chung khoan',
  'Trang thiet bi y te',
  'Nong san, thuy san, Don Dien',
  'Cong ty chung khoan',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cong ty chung khoan',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Nong san, thuy san, Don Dien',
  'Thiet bi, vat lieu xay dung',
  'Dich vu Dau tu',
  'Ngan hang',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cong ty bao hiem',
  'Xay dung, xay lap',
  'Cong ty chung khoan',
  'Tham do va san xuat dau khi',
  'Ngan hang',
  'Cong ty bao hiem',
  'Cong ty chung khoan',
  'Xay dung, xay lap',
  'Xay dung, xay lap',
  'Nong san, thuy san, Don Dien',
  'Xay dung, xay lap',
  'Ban le tong hop',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Xay dung, xay lap',
  'Cong nghe phan cung',
  'Nong san, thuy san, Don Dien',
  'Dich vu bat Dong san',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Dich vu giai tri',
  'Xay dung, xay lap',
  'O to',
  'Ngan hang',
  'Xay dung, xay lap',
  'Vien thong co Dinh',
  'Cong ty chung khoan',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Khach san',
  'San pham thuc pham',
  'Duoc pham',
  'Hoa chat chuyen dung',
  'Cac linh kien va thiet bi Dien',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Ban le tong hop',
  'Giay',
  'Khai khoang chung',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Dich vu van tai',
  'Dich vu bat Dong san',
  'Xay dung, xay lap',
  'Hoa chat chuyen dung',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Lop',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Xay dung, xay lap',
  'Thiet bi, vat lieu xay dung',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Dich vu bat Dong san',
  'Quy mo',
  'Ngan hang',
  'Dich vu internet',
  'Ngan hang',
  'Xay dung, xay lap',
  'Cong ty chung khoan',
  'Xay dung, xay lap',
  'Dich vu bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cong nghe phan mem',
  'Ban le tong hop',
  'Cong ty chung khoan',
  'Quy mo',
  'Xay dung, xay lap',
  'Phan phoi khi Dot',
  'San xuat va cung cap Dien truyen thong',
  'Cac linh kien va thiet bi Dien',
  'Quan ao va Do phu kien',
  'Dich vu van tai',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Nong san, thuy san, Don Dien',
  'Dich vu van tai',
  'O to',
  'Xay dung, xay lap',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Cong ty chung khoan',
  'Ngan hang',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Giay',
  'Dich vu van tai',
  'Dich vu van tai',
  'O to',
  'Xay dung, xay lap',
  'Nong san, thuy san, Don Dien',
  'Thep',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Thep',
  'Thiet bi, vat lieu xay dung',
  'Xay dung, xay lap',
  'Xay dung, xay lap',
  'Nong san, thuy san, Don Dien',
  'Xay dung, xay lap',
  'Hang khong cho khach',
  'Dich vu Dau tu',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Nong san, thuy san, Don Dien',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Dich vu Dau tu',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Trang thiet bi y te',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'San pham thuc pham',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Dich vu bat Dong san',
  'Dich vu bat Dong san',
  'Thiet bi, vat lieu xay dung',
  'Khai khoang chung',
  'Xay dung, xay lap',
  'Hoa chat chuyen dung',
  'Xay dung, xay lap',
  'Khai khoang chung',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Xay dung, xay lap',
  'Xay dung, xay lap',
  'Ban le tong hop',
  'Ngan hang',
  'Ngan hang',
  'San pham gia dung lau ben',
  'Cong ty chung khoan',
  'San pham thuc pham',
  'Cong ty bao hiem',
  'Ngan hang',
  'San pham thuc pham',
  'Xay dung, xay lap',
  'Ban le tong hop',
  'Thiet bi, vat lieu xay dung',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Xay dung, xay lap',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Nong san, thuy san, Don Dien',
  'Thep',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'San xuat va cung cap Dien truyen thong',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Ngan hang',
  'Tham do va san xuat dau khi',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Khach san',
  'Cong ty chung khoan',
  'Nong san, thuy san, Don Dien',
  'Xay dung, xay lap',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Ban le tong hop',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Xay dung, xay lap',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Hoa chat co ban - San pham nhua, cao su, hoa chat',
  'Tham do va san xuat dau khi',
  'Quan ao va Do phu kien',
  'Thep',
  'San xuat va cung cap Dien truyen thong',
  'Nhien lieu thay the',
  'Ong dan dau khi',
  'Thiet bi, dich vu khai thac dau mo',
  'Thiet bi, dich vu khai thac dau mo',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Van tai bien',
  'Thiet bi, dich vu khai thac dau mo',
  'Van tai bien',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Xay dung, xay lap',
  'Hoa chat chuyen dung',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'San pham thuc pham',
  'San xuat va cung cap Dien truyen thong',
  'May cong nghiep',
  'Xay dung, xay lap',
  'Bia',
  'Thiet bi vien thong',
  'Cong ty chung khoan',
  'San pham thuc pham',
  'Xay dung, xay lap',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Ngan hang',
  'San pham gia dung lau ben',
  'Cong ty chung khoan',
  'Nong san, thuy san, Don Dien',
  'Dich vu van tai',
  'Thep',
  'Cong nghe phan mem',
  'Ngan hang',
  'Cong ty chung khoan',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'San pham thuc pham',
  'Ngan hang',
  'Quan ao va Do phu kien',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'San pham thuc pham',
  'Ngan hang',
  'Dich vu van tai',
  'Dich vu bat Dong san',
  'Cong ty chung khoan',
  'Quan ao va Do phu kien',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cung cap nuoc sach',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Dich vu Dau tu',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'San pham gia dung khong lau ben',
  'Thep',
  'Quan ao va Do phu kien',
  'Khai khoang chung',
  'Ngan hang',
  'Cac thiet bi Dien tu',
  'Hoa chat chuyen dung',
  'Thiet bi, vat lieu xay dung',
  'San xuat va cung cap Dien truyen thong',
  'Noi that',
  'Ban le tong hop',
  'Cong ty chung khoan',
  'Quan ly tai san',
  'Thep',
  'Xay dung, xay lap',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Ngan hang',
  'Xay dung, xay lap',
  'Cong ty chung khoan',
  'Cong ty chung khoan',
  'Thiet bi, vat lieu xay dung',
  'Thiet bi vien thong',
  'Quan ao va Do phu kien',
  'Thep',
  'Nong san, thuy san, Don Dien',
  'San pham thuc pham',
  'Dich vu bat Dong san',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Ngan hang',
  'Cac cong ty Dau co va phat trien bat Dong san',
  'Cong ty chung khoan',
  'Van tai bien',
  'Cong ty chung khoan',
  'Hang khong cho khach',
  'Linh kien oto',
  'Cong ty chung khoan',
  'Xay dung, xay lap',
  'San pham thuc pham',
  'Ngan hang',
  'Van tai bien',
  'Khai khoang chung',
  'Dich vu bat Dong san',
  'Dich vu bat Dong san',
  'San xuat va cung cap Dien truyen thong',
  'Dich vu buu chinh',
  'Cong ty chung khoan',
];
export const TICKERS_MAPPINGS = () => {
  return TRADINGS.map((item, index) => ({
    id: index + 1,
    trading: item,
    ticker: TICKERS[index],
    color: COLORS[index],
    name: `${item} - ${names[index]}`,
  }));
};
